In [ ]:
Q1. Create one variable containing following type of data:
(i) string
(ii) list
(iii) float
(iv) tuple
Ans:- # (i) String
my_string = "Hello, World!"

# (ii) List
my_list = [1, 2, 3, 4, 5]

# (iii) Float
my_float = 3.14

# (iv) Tuple
my_tuple = (10, 20, 30)

In [ ]:
Q2. Given are some following variables containing data:
(i) var1 = ‘ ‘
(ii) var2 = ‘[ DS , ML , Python]’
(iii) var3 = [ ‘DS’ , ’ML’ , ‘Python’ ]
(iv) var4 = 1.
What will be the data type of the above given variable.
Ans:- (i) var1 = ' ': This variable contains a single space character, which makes it a string.
    (ii) var2 = '[ DS , ML , Python]': This variable contains a string representation of a list 
with elements separated by commas. Even though it resembles a list, it is still a string due to 
the  enclosing single quotes. The individual elements are not enclosed in quotes or defined as 
valid Python objects, so it remains a string.
    (iii) var3 = ['DS', 'ML', 'Python']: This variable contains a list of strings. The elements are
enclosed in square brackets, and each element is a string. Therefore, it is a list.
    (iv) var4 = 1.: This variable contains a floating-point number. In Python, any number with a 
decimal point is considered a float.

In [ ]:
Q3. Explain the use of the following operators using an example:
(i) /
(ii) %
(iii) //
(iv) **
Ans:- (i) / (Division Operator): The division operator / is used to perform regular division between 
two numbers. It returns the quotient as a floating-point number.
Example:
# Regular division
result = 10 / 3
print(result)  # Output: 3.3333333333333335
    (ii) % (Modulo Operator): The modulo operator % is used to find the remainder after the division
of two numbers. It is often used to check divisibility or to wrap values around a certain range.
Example:
# Modulo operator
remainder = 10 % 3
print(remainder)  # Output: 1
    (iii) // (Floor Division Operator): The floor division operator // is used to perform division 
between two numbers and rounds down the result to the nearest integer, discarding any fractional part.
The result is always an integer, even if the numbers involved are floats.
Example:
# Floor division
result = 10 // 3
print(result)  # Output: 3
    (iv) ** (Exponentiation Operator): The exponentiation operator ** is used to raise a number to a 
certain power.
Example:
# Exponentiation
result = 2 ** 3
print(result)  # Output: 8

In [ ]:
Q4. Create a list of length 10 of your choice containing multiple types of data. Using for loop print 
the element and its data type.
Ans:- Sure, here's an example of creating a list with multiple types of data and using a for loop to 
print each element along with its data type:
Ans:- 
# Create a list with multiple types of data
my_list = [1, 2.5, "Hello", True, [10, 20], {"name": "John", "age": 30}, None, (1, 2), False, "Python"]

# Use a for loop to print each element and its data type
for element in my_list:
    print(f"Element: {element}, Data Type: {type(element).__name__}")

Output:-
Element: 1, Data Type: int
Element: 2.5, Data Type: float
Element: Hello, Data Type: str
Element: True, Data Type: bool
Element: [10, 20], Data Type: list
Element: {'name': 'John', 'age': 30}, Data Type: dict
Element: None, Data Type: NoneType
Element: (1, 2), Data Type: tuple
Element: False, Data Type: bool
Element: Python, Data Type: str

In [ ]:
Q5. Using a while loop, verify if the number A is purely divisible by number B and if so then how many
times it can be divisible.
Ans:- Code
# Input numbers
A = 24
B = 3
# Initialize a count variable to keep track of how many times A can be divided by B
count = 0
# Verify if A is divisible by B using a while loop
while A >= B:
    A = A - B
    count += 1
# Print the result
if A == 0:
    print(f"{A} is purely divisible by {B}. It can be divided {count} times.")
else:
    print(f"{A} is not purely divisible by {B}. The division leaves a remainder.")

Output:

In [ ]:
Q6. Create a list containing 25 int type data. Using for loop and if-else condition print if the element is divisible
by 3 or not.
Ans:- Sure, let's create a list containing 25 integer-type data and then use a for loop with an if-else condition to 
check if each element is divisible by 3 or not. Here's the code:
# Create a list containing 25 integer-type data
my_list = [1, 6, 9, 15, 22, 27, 33, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125]

# Use a for loop and if-else condition to check divisibility by 3
for num in my_list:
    if num % 3 == 0:
        print(f"{num} is divisible by 3.")
    else:
        print(f"{num} is not divisible by 3.")

Output:-
1 is not divisible by 3.
6 is divisible by 3.
9 is divisible by 3.
15 is divisible by 3.
22 is not divisible by 3.
27 is divisible by 3.
33 is divisible by 3.
40 is not divisible by 3.
45 is divisible by 3.
50 is not divisible by 3.
55 is not divisible by 3.
60 is divisible by 3.
65 is not divisible by 3.
70 is not divisible by 3.
75 is divisible by 3.
80 is not divisible by 3.
85 is not divisible by 3.
90 is divisible by 3.
95 is not divisible by 3.
100 is not divisible by 3.
105 is divisible by 3.
110 is not divisible by 3.
115 is not divisible by 3.
120 is divisible by 3.
125 is not divisible by 3.

In [ ]:
Q7. What do you understand about mutable and immutable data types? Give examples for both showing this property.

In [ ]:
Ans:- Mutable and immutable are properties of data types in programming languages like Python. These properties
define whether the data stored in a variable of a particular data type can be modified after its creation. Let's
explain both concepts and provide examples for each:
    <i> Mutable Data Types: Mutable data types are those whose values can be changed or modified after creation.
This means that you can update, add, or remove elements from a mutable object without creating a new object. Lists
and dictionaries in Python are examples of mutable data types.
Example of a mutable data type:
# Lists are mutable
my_list = [1, 2, 3, 4]
print("Original List:", my_list)
# Update an element
my_list[2] = 10
print("Modified List:", my_list)
# Add an element
my_list.append(5)
print("List after adding element:", my_list)
# Remove an element
my_list.remove(2)
print("List after removing element:", my_list)

Output:-
Original List: [1, 2, 3, 4]
Modified List: [1, 2, 10, 4]
List after adding element: [1, 2, 10, 4, 5]
List after removing element: [1, 10, 4, 5]

    <ii> Immutable Data Types: Immutable data types are those whose values cannot be changed or modified after
creation. Once an immutable object is created, you cannot change its content. Examples of immutable data types in
Python include integers, floats, strings, and tuples.
Example of an immutable data type:
# Strings are immutable
my_string = "Hello"
print("Original String:", my_string)
# Attempting to update a character (this will raise an error)
# my_string[0] = "h"
# Concatenating to create a new string
new_string = my_string + " World!"
print("New String:", new_string)
# The original string remains unchanged
print("Original String after concatenation:", my_string)

Output:-
Original String: Hello
New String: Hello World!
Original String after concatenation: Hello